In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print("hello")

Matplotlib is building the font cache; this may take a moment.

hello

In [35]:
x = pd.read_csv("data.csv")
x

,Log_ID,User_ID,Log_Date,Activity_Type,Duration_Minutes,Calories_Burned,Steps_Count,Avg_Heart_Rate_BPM,Sleep_Hours,Water_Intake_Liters,Mood_Rating
0,LOG-502564,USR-2160,2024-01-01,Gym Workout,118,243,9219,160,5.4,3.6,5
1,LOG-502968,USR-2237,2024-01-01,Cycling,32,588,11088,150,4.3,1.2,4
2,LOG-503489,USR-2157,2024-01-01,Cycling,23,198,9557,157,7.5,1.7,5
3,LOG-503464,USR-2040,2024-01-01,Yoga,107,832,3044,152,4.8,2.6,2
4,LOG-503429,USR-2084,2024-01-01,HIIT,87,113,16114,111,4.1,0.8,5
...,...,...,...,...,...,...,...,...,...,...,...
3495,LOG-501088,USR-2179,2024-12-31,Gym Workout,43,520,10574,152,5.1,2.2,3
3496,LOG-500706,USR-2200,2024-12-31,Gym Workout,94,704,3945,74,5.6,1.7,4
3497,LOG-503184,USR-2102,2024-12-31,Swimming,28,797,1118,110,6.2,3.4,5
3498,LOG-502469,USR-2231,2024-12-31,Yoga,41,860,6556,100,4.6,1.4,4
3499,LOG-502716,USR-2143,2024-12-31,Swimming,42,88,9231,120,7.5,1.1,3

In [36]:
x.columns

Index(['Log_ID', 'User_ID', 'Log_Date', 'Activity_Type', 'Duration_Minutes',
       'Calories_Burned', 'Steps_Count', 'Avg_Heart_Rate_BPM', 'Sleep_Hours',
       'Water_Intake_Liters', 'Mood_Rating'],
      dtype='str')

In [37]:
x.shape

(3500, 11)

In [38]:
x.describe

<bound method NDFrame.describe of           Log_ID   User_ID    Log_Date Activity_Type  Duration_Minutes  \
0     LOG-502564  USR-2160  2024-01-01   Gym Workout               118
1     LOG-502968  USR-2237  2024-01-01       Cycling                32
2     LOG-503489  USR-2157  2024-01-01       Cycling                23
3     LOG-503464  USR-2040  2024-01-01          Yoga               107
4     LOG-503429  USR-2084  2024-01-01          HIIT                87
...          ...       ...         ...           ...               ...
3495  LOG-501088  USR-2179  2024-12-31   Gym Workout                43
3496  LOG-500706  USR-2200  2024-12-31   Gym Workout                94
3497  LOG-503184  USR-2102  2024-12-31      Swimming                28
3498  LOG-502469  USR-2231  2024-12-31          Yoga                41
3499  LOG-502716  USR-2143  2024-12-31      Swimming                42

      Calories_Burned  Steps_Count  Avg_Heart_Rate_BPM  Sleep_Hours  \
0                 243         9219                 160          5.4
1                 588        11088                 150          4.3
2                 198         9557                 157          7.5
3                 832         3044                 152          4.8
4                 113        16114                 111          4.1
...               ...          ...                 ...          ...
3495              520        10574                 152          5.1
3496              704         3945                  74          5.6
3497              797         1118                 110          6.2
3498              860         6556                 100          4.6
3499               88         9231                 120          7.5

      Water_Intake_Liters  Mood_Rating
0                     3.6            5
1                     1.2            4
2                     1.7            5
3                     2.6            2
4                     0.8            5
...                   ...          ...
3495                  2.2            3
3496                  1.7            4
3497                  3.4            5
3498                  1.4            4
3499                  1.1            3

[3500 rows x 11 columns]>

In [39]:
x.head()

,Log_ID,User_ID,Log_Date,Activity_Type,Duration_Minutes,Calories_Burned,Steps_Count,Avg_Heart_Rate_BPM,Sleep_Hours,Water_Intake_Liters,Mood_Rating
0,LOG-502564,USR-2160,2024-01-01,Gym Workout,118,243,9219,160,5.4,3.6,5
1,LOG-502968,USR-2237,2024-01-01,Cycling,32,588,11088,150,4.3,1.2,4
2,LOG-503489,USR-2157,2024-01-01,Cycling,23,198,9557,157,7.5,1.7,5
3,LOG-503464,USR-2040,2024-01-01,Yoga,107,832,3044,152,4.8,2.6,2
4,LOG-503429,USR-2084,2024-01-01,HIIT,87,113,16114,111,4.1,0.8,5

In [40]:
x.tail()

,Log_ID,User_ID,Log_Date,Activity_Type,Duration_Minutes,Calories_Burned,Steps_Count,Avg_Heart_Rate_BPM,Sleep_Hours,Water_Intake_Liters,Mood_Rating
3495,LOG-501088,USR-2179,2024-12-31,Gym Workout,43,520,10574,152,5.1,2.2,3
3496,LOG-500706,USR-2200,2024-12-31,Gym Workout,94,704,3945,74,5.6,1.7,4
3497,LOG-503184,USR-2102,2024-12-31,Swimming,28,797,1118,110,6.2,3.4,5
3498,LOG-502469,USR-2231,2024-12-31,Yoga,41,860,6556,100,4.6,1.4,4
3499,LOG-502716,USR-2143,2024-12-31,Swimming,42,88,9231,120,7.5,1.1,3

In [41]:
x["Calories_Burned"].mean()

np.float64(478.9757142857143)